version: '3'

services:

  #The website container
  web:
    build: ./Website
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"

  #The backend container
  backend:
    build: ./Website
    #command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    #ports:
    #  - "80:8000"
