version: '3'

services:
  #The website container
  web:
    build: ./Website
    volumes:
      - ./Website:/code
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

  #The backend container
  backend:
    build: ./Grader
    volumes:
      - ./Grader:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - "5000:5000"
    command: python3 grader.py
  runner:
    build: ./CodeRunner

