version: '3'

services:
  # Main website
  website:
    build: ./Website
    image: website
    volumes:
      - ./Website:/code
      - ./Website/media:/code/media
      - /tmp:/tmp
    expose:
      - "8000"
    links:
      - backend:backend
      - redis:redis
      - postgres:postgres
    environment:
      - "DJANGO_PRODUCTION=1"
      - "DJANGO_SECRET_KEY=/code/secret_key.txt"
    restart: on-failure
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"


  # Spin-off CodeRunners at request of main website container
  backend:
    build: ./Grader
    image: backend
    volumes:
      - ./Grader:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Website/media:/code/media:ro
      - /tmp:/tmp
    expose:
      - "5000"
    restart: on-failure
    command: python3 grader.py


  # CodeRunner is environment in which submissions are run.  It's included in compose file to force it to build.
  runner:
    build: ./CodeRunner
    image: runner
    volumes:
      - /tmp:/tmp:ro


  # Nginx for front end, gets redirected to django
  nginx:
    restart: on-failure
    build: ./Nginx/
    image: nginx:django
    depends_on:
      - website
    ports:
      - "80:80"
    #  - "443:443"
    #     volumes:
    #        - ./code/static:/static
    links:
      - website:website


  # Redis for django channels      
  redis:
    image: redis
    expose: 
      - "6379"


  # Database
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - ./Postgres:/var/lib/postgresql/data
    expose:
      - "5432"


  # Serve static files in production
  fileserver:
    image: halverneus/static-file-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Website/static:/web
    environment:
      - "PORT=8080"
      - "SHOW_LISTING=false"
    restart: on-failure
