version: '3'

services:
  # The website container
  website:
    build: ./Website
    volumes:
      - ./Website:/code
      - /tmp:/tmp
    ports:
      - "8000:8000"
    network_mode: host
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000

  # The backend container
  backend:
    build: ./Grader
    volumes:
      - ./Grader:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp:ro
    ports:
      - "5000:5000"
    network_mode: host
    restart: always
    command: python3 grader.py
  
  # Runner container, will immediatley exit
  runner:
    build: ./CodeRunner
    volumes:
      - /tmp:/tmp:ro
