version: '3'

services:
  # Main website
  website:
    build: ./Website
    image: website
    depends_on:
      - postgres
    volumes:
      - ./Website:/code
      - ./Website/media:/code/media
      - /tmp:/tmp
      - ./secret_key.txt:/code/secret_key.txt:ro
    expose:
      - "8000"
    environment:
      #- "DJANGO_PRODUCTION=1"
      - "DJANGO_SECRET_KEY=/code/secret_key.txt"
      - "VIRTUAL_HOST=localhost"
    restart: on-failure
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && python3 manage.py runserver 0.0.0.0:8000"
    restart: on-failure


  # Spin-off CodeRunners at request of main website container
  grader:
    build: ./Grader
    image: grader
    volumes:
      - ./Grader:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Website/media:/code/media:ro
      - /tmp:/tmp
    expose:
      - "5000"
    restart: on-failure
    command: python3 grader.py
    restart: on-failure


  # CodeRunner is environment in which submissions are run.  It's included in compose file to force it to build.
  coderunner:
    build: ./CodeRunner
    image: coderunner
    volumes:
      - /tmp:/tmp:ro


  # Nginx for front end, gets redirected to django
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - website
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure


  # Redis for django channels      
  redis:
    image: redis
    expose: 
      - "6379"
    restart: on-failure


  # Database
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - ./Postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: on-failure


  # Serve static files in production
  fileserver:
    image: halverneus/static-file-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Website/static:/web
    environment:
      - "PORT=8080"
      - "SHOW_LISTING=false"
    restart: on-failure
