version: '3'

services:
  #The website container
  web:
    build: ./Website
    volumes:
      - ./Website:/code
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

  #The backend container
  backend:
    build: ./Grader
    volumes:
      - ./Grader:/code
    ports:
     - "80:8000"
     #command: python3 // Run a webserver to handle grade me requests
