version: '3'

services:
  # The website container
  website:
    build: ./Website
    image: website
    volumes:
      - ./Website:/code
      - ./Website/media:/code/media
      - /tmp:/tmp
    expose:
      - "8000"
    links:
      - backend:backend
      - redis:redis
      - postgres:postgres
    restart: on-failure
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"






  # The backend container
  backend:
    build: ./Grader
    image: backend
    volumes:
      - ./Grader:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Website/media:/code/media:ro
      - /tmp:/tmp
    expose:
      - "5000"
    restart: on-failure
    command: python3 grader.py




  
  # Runner container, will immediatley exit
  runner:
    build: ./CodeRunner
    image: runner
    volumes:
      - /tmp:/tmp:ro






  # Nginx for front end, gets redirected to django
  nginx:
    restart: on-failure
    build: ./Nginx/
    image: nginx:django
    depends_on:
      - website
    ports:
      - "80:80"
    #  - "443:443"
    #     volumes:
    #        - ./code/static:/static
    links:
      - website:website


  # Redis for django channels      
  redis:
    image: redis
    expose: 
      - "6379"

  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - ./Postgres:/var/lib/postgresql/data
    expose:
      - "5432"
